site_name: skeleton-ts
extra_javascript:
  - lib/mermaid.min.js
extra_css:
  - lib/mermaid.css
markdown_extensions:
  - codehilite
nav:
  - Home: index.md
  - Project Sturcture:
      - Overview: project-structure/overview.md
      - Dependency Injection: project-structure/di.md
  - Workflow:
      - Writing Documentation: workflow/doc.md
  - About:
      - Author: about/author.md
theme:
  name: material
