site_name: skeleton-ts
extra_javascript:
  - lib/mermaid.min.js
extra_css:
  - lib/mermaid.css
markdown_extensions:
  - codehilite
nav:
  - Home: index.md
  - Project Sturcture:
      - Overview: project-structure/overview.md
      - Dependency Injection: project-structure/di.md
  - Workflow:
      - Overview: workflow/overview.md
      - Writing Documentation: workflow/doc.md
      - Development: workflow/development.md
      - Unit Testing: workflow/unit-testing.md
      - Integration Testing: workflow/integration-testing.md
      - Deployment: workflow/deployment.md
      - Monitoring: workflow/monitoring.md
  - About:
      - Author: about/author.md
theme:
  name: material
